FROM bitnami/python
# 2023-02-11  -  bitnami/python  latest  c5757b37ea2c  645MB
# Version: 3.11.2
# Base OS flavor: debian-11
# Compressed size: 218MB
# Entrypoint: "python"

# TODO: Entry point will become the startup command for flask or possibly supervisord to manage flask start/restart.

# TODO: This image size seems large. It should be possible to shrink it substantially.
#  Plan is to remove uneeded-content from the image and assess before considering other base images.
#  I want to avoid using an Alpine base image for security and other reasons.

