FROM bitnami/postgresql:latest
# 2023-02-10  -  bitnami/postgresql  latest  f576e9b9b432  275MB
# Version: 15.2.0
# Base OS flavor: debian-11
# Compressed size: 88MB
# Data directory: /bitnami/postgresql
# Entrypoint: "/opt/bitnami/scripts/postgresql/run.sh"

